name: Main WorkFlow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      id: setup-java

  build:
    runs-on: windows-latest
    needs: setup-java
    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  run-specific-test:
    runs-on: windows-latest
    needs: 
      - build
      - setup-java
    steps:
    - uses: actions/checkout@v3
    - name: Run specific test
      run: mvn -B test -Dtest=SignInTest --file pom.xml
